module.exports = {
  eventTemplate: {
    id: "Event Id",
    region: "Region",
    channelLink: "Channel Link",
    poster: "Poster",
    name: "Event Name",
    caption: "Caption",
    description: "Description",
    note: "Note",
    registrationLink: "Registration Link",
    eventDate: "Event Date",
    eventTiming: "Event Timing",
    startDate: "Start Date",
    endDate: "End Date",
    startTime: "Start Time",
    endTime: "End Time",
    location: "Location",
    mapUrl: "Map Url",
    floor: "Floor",
    locationNote: "Location Note",
    organizer: "Organizer Telegram",
    communityName: "Community or Company Name",
    communityTg: "Community or Company Telegram url",
    websiteUrl: "Website Url",
    messageId: "Message Id",
    singleDayEvent: true,
  },
};
