module.exports = {
  EVENT_POSTER: "event_poster",
  EVENT_NAME: "event_name",
  EVENT_CAPTION: "event_caption",
  EVENT_DESCRIPTION: "event_description",
  EVENT_NOTE: "event_note",
  EVENT_REG_LINK: "event_reg_link",
  EVENT_DATE: "event_date",
  EVENT_SINGLE_DATE: "event_single_date",
  EVENT_MULTIPLE_DATE: "event_multiple_date",
  EVENT_TIMING: "event_timing",
  EVENT_LOCATION: "event_location",
  EVENT_MAP_URL: "event_map_url",
  EVENT_FLOOR: "event_floor",
  EVENT_LOCATION_NOTE: "event_location_note",
  EVENT_ORGANIZER: "event_organizer",
  EVENT_COMMUNITY_NAME: "event_community_name",
  EVENT_COMMUNITY_TG: "event_community_tg",
  EVENT_WEBSITE_URL: "event_website_url",
};
